# API server configuration only
# Server, CORS, and request settings

# Server settings
server:
  title: "Dynamic Lead Generation API"
  version: "1.0.0"
  description: "AI-powered adaptive forms for lead generation"
  host: "0.0.0.0"
  port: 8000
  development:
    reload: true
    workers: 1
  staging:
    reload: false
    workers: 2
  production:
    reload: false
    workers: 4

# CORS settings
cors:
  development:
    origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
      - "http://localhost:8080"
  staging:
    origins:
      - "https://staging.yourapp.com"
      - "http://localhost:3000"
  production:
    origins:
      - "https://yourapp.com"
      - "https://www.yourapp.com"
  methods:
    - "GET"
    - "POST"
    - "PUT" 
    - "DELETE"
    - "OPTIONS"
  headers:
    - "*"
  credentials: true

# Request handling
request:
  development:
    max_size: 10485760  # 10MB
    timeout: 30
    keep_alive: 5
  staging:
    max_size: 8388608   # 8MB
    timeout: 35
    keep_alive: 5
  production:
    max_size: 5242880   # 5MB
    timeout: 45
    keep_alive: 10