api:
  title: 'Dynamic Multi-Step Forms'
  version: '0.1.0'
  description: 'Dynamic lead gen'
  host: '0.0.0.0'
  port: 8000
  reload: true

environment:
  name: 'development'
  debug: true
  log_level: 'INFO'

security:
  cors_origins:
    - 'http://localhost:3000'
    - 'http://127.0.0.1:3000'
    - 'http://localhost:8080'
