# Development Docker Compose configuration
# For local development with hot reload and debugging

services:
  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dynamic-survey-api:dev
    container_name: survey-backend-dev

    # Load environment variables from .env file
    env_file:
      - .env

    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - AUTO_RELOAD=true
      # Database config - use Supabase
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      # Redis config
      - REDIS_URL=redis://redis:6379
      # LLM config
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Optional for development
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

    ports:
      - "${BACKEND_PORT:-8000}:8000"

    volumes:
      # Mount source code for hot reload (but preserve venv)
      - ./backend/app:/app/app
      - ./backend/pydantic_models.py:/app/pydantic_models.py
      - ./backend/config:/app/config
      - ./backend/logging_config.py:/app/logging_config.py
      - backend_cache:/app/data/cache
      - uploads_data:/app/uploads

    networks:
      - survey_network

    depends_on:
      - redis

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Development with hot reload)
  frontend:
    build:
      context: ./frontend/form-app
      dockerfile: Dockerfile.dev  # Development Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
        - VITE_ENVIRONMENT=development
    image: dynamic-survey-frontend:dev
    container_name: survey-frontend-dev

    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true  # For file watching in Docker

    ports:
      - "${FRONTEND_PORT:-5173}:5173"

    volumes:
      # Mount source code for hot reload
      - ./frontend/form-app/src:/app/src
      - ./frontend/form-app/public:/app/public
      - ./frontend/form-app/package.json:/app/package.json
      - frontend_node_modules:/app/node_modules

    networks:
      - survey_network

    depends_on:
      - backend

  # Admin Frontend (Development with hot reload)
  admin:
    build:
      context: ./frontend/admin-app
      dockerfile: Dockerfile.dev  # Development Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
        - VITE_ENVIRONMENT=development
    image: dynamic-survey-admin:dev
    container_name: survey-admin-dev

    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true  # For file watching in Docker

    ports:
      - "${ADMIN_PORT:-5174}:5174"

    volumes:
      # Mount source code for hot reload
      - ./frontend/admin-app/src:/app/src
      - ./frontend/admin-app/public:/app/public
      - ./frontend/admin-app/package.json:/app/package.json
      - ./frontend/admin-app/vite.config.ts:/app/vite.config.ts
      - ./frontend/admin-app/index.html:/app/index.html
      - admin_node_modules:/app/node_modules

    networks:
      - survey_network

    depends_on:
      - backend

  # Redis for development caching
  redis:
    image: redis:7-alpine
    container_name: survey-redis-dev

    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - survey_network

# Named volumes for development
volumes:
  backend_cache:
    driver: local
  frontend_node_modules:
    driver: local
  admin_node_modules:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local

# Network configuration
networks:
  survey_network:
    driver: bridge
